package com.bibliotheca.spring_boot_library.entity;

import javax.persistence.Column; // Importing JPA Column annotation for mapping class fields to database columns
import javax.persistence.Entity; // Importing JPA Entity annotation to define a class as a database entity
import javax.persistence.GeneratedValue; // Importing JPA GeneratedValue annotation for auto-generating primary key values
import javax.persistence.GenerationType; // Importing GenerationType for specifying the primary key generation strategy
import javax.persistence.Id; // Importing JPA Id annotation to indicate the primary key field
import javax.persistence.Table; // Importing JPA Table annotation for specifying the table name in the database

import lombok.Data; // Importing Lombok to automatically generate getters, setters, and other utility methods

/**
 * Represents a payment record in the library system.
 * This class is mapped to the "payment" table in the database and contains details about user payments.
 */
@Entity // Denotes that this class is a JPA entity, mapped to a database table
@Table(name = "payment") // Specifies the name of the table in the database that this entity will correspond to
@Data // Lombok annotation to automatically generate getters, setters, and other utility methods
public class Payment {

    @Id // Indicates that this field is the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the primary key value will be automatically generated by the database
    @Column(name = "id") // Maps this field to the "id" column in the database
    private Long id; // Unique identifier for each payment record

    @Column(name = "user_email") // Maps this field to the "user_email" column in the database
    private String userEmail; // Email address of the user associated with this payment

    @Column(name = "amount") // Maps this field to the "amount" column in the database
    private double amount; // The amount of money paid by the user
}
