package com.bibliotheca.spring_boot_library.entity;

import java.util.Date; // Importing Date class for handling date and time

import javax.persistence.Column; // Importing JPA Column annotation for mapping class fields to database columns
import javax.persistence.Entity; // Importing JPA Entity annotation to define a class as a database entity
import javax.persistence.GeneratedValue; // Importing JPA GeneratedValue annotation for auto-generating primary key values
import javax.persistence.GenerationType; // Importing GenerationType for specifying the primary key generation strategy
import javax.persistence.Id; // Importing JPA Id annotation to indicate the primary key field
import javax.persistence.Table; // Importing JPA Table annotation for specifying the table name in the database

import org.hibernate.annotations.CreationTimestamp; // Importing CreationTimestamp for automatically setting creation timestamp

import lombok.Data; // Importing Lombok to automatically generate getters, setters, and other utility methods

/**
 * Represents a review submitted by users for books in the library system.
 * This class is mapped to the "review" table in the database and contains details about user reviews.
 */
@Entity // Denotes that this class is a JPA entity, mapped to a database table
@Table(name = "review") // Specifies the name of the table in the database that this entity will correspond to
@Data // Lombok annotation to automatically generate getters, setters, and other utility methods
public class Review {

    @Id // Indicates that this field is the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the primary key value will be automatically generated by the database
    @Column(name = "id") // Maps this field to the "id" column in the database
    private Long id; // Unique identifier for each review record

    @Column(name = "user_email") // Maps this field to the "user_email" column in the database
    private String userEmail; // Email address of the user who submitted the review

    @Column(name = "date") // Maps this field to the "date" column in the database
    @CreationTimestamp // Automatically sets the date field to the current date when the review is created
    private Date date; // Date when the review was submitted

    @Column(name = "rating") // Maps this field to the "rating" column in the database
    private double rating; // Rating given by the user for the book (e.g., out of 5)

    @Column(name = "book_id") // Maps this field to the "book_id" column in the database
    private Long bookId; // Identifier of the book for which the review is submitted

    @Column(name = "review_description") // Maps this field to the "review_description" column in the database
    private String reviewDescription; // Optional description of the review provided by the user
}
